directories:
  output: release
  buildResources: build
appId: com.xin.notes
productName: Xin
files:
  - filter:
      - dist/**/*
mac:
  category: public.app-category.productivity
  icon: build/icon.icns
  target: dmg
electronVersion: 39.2.5
